version: '3.8'

services:
  db:
    image:  postgres:17.4-alpine3.21
    container_name: postgres_db
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: django_docker
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: adminadminadmin

    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mn
    env_file:
      - .env

  web:
    build: .
    container_name: docker-django
    restart: always
    ports: 
      - "8000:8000"
    depends_on:
      - db
    networks:
      - mn
    environment:
      DB_HOST: db

volumes:
  postgres_data:

networks:
  mn:
    driver: bridge