# Generated by Django 5.2.4 on 2025-07-16 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_courseenrollment_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('totalCollectionAmount', models.PositiveIntegerField(default=0)),
                ('totalCollectedAmount', models.PositiveBigIntegerField(default=0)),
                ('totalCreditAmount', models.PositiveBigIntegerField(default=0)),
            ],
        ),
    ]
