# Generated by Django 5.2 on 2025-04-09 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_creator_options_alter_creator_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
