# Generated by Django 5.1.7 on 2025-03-21 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='creator',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
